language: python
dist: xenial
os: linux

python:
  - "3.7"

install: pip install -r requirements.txt
script: py.test

deploy:
  provider: pypi
  username: mfreeborn
  password: VVMt0lixga3Gli0UU9JODocbxGL6e4SeXQ/PpBRUok0lOorp6mf5zwykla0iQhkRkray9E9z8L9zlWbC1NM9fUbsZtZW3LH6xKdmdk+y5f03VkKpu0lvPJq0C6qp346C6K19vLHswEY3JZczwHhB6w2NTK4CKjMMdGXcaissEURF8QnBspSPS8lRvAcfpLNnoBonrEzOWd5LUf1uTPVksXsFegHRUfmZIo9bUOCtyXtHFtsEpXdSp5oYeGwZ/+mE3NwDC9nIV2uLJhQmR9RA4/Qx+xErfhvjIEIbCmy6VgYz4pDA73jW/rimpsuiaO6iYGvFdnV0A8R59H3VPeB1LsUbpqFsyZbnXWhW9FgFFqQeYPSlOCstOb9bsDc5JPnttOfA4Xsqsr4/wfWp2x1p4nNlBdZkZTZ7rz1UKbygmwispE0Dcoq+xblTIC9U4WBr9nbJKYPQGfy4wpsh9P2vCtR00DhxwtNpVNXwm5s5AiDixCMWmnXKxO1bUvDhHHiEgRMQGs9qWX0kPeCCwmrZIIv3TTY1A5F8yXg0gOXIdLd3KUY4+Z3Lh75DAtT8aXNk0tnH87+BlumHLORgjnDWMiaZWPzWNfutlMp5RjrXCYI9pD/kZFcejNDeqBQ2yFYcvBuBdF4dDT+ZG/qAUB+NKdlZd+AC5TzyHbn4uKhtduM=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  edge: true
  on:
    tags: true
