language: python
dist: xenial
os: linux
python:
- '3.7'
install: pip install -r requirements.txt
script: py.test
deploy:
  provider: pypi
  username: "__user__"
  password:
    secure: YgZIyTKhwitUslNze6e9wZJbfv8dMam0vQ0JU/Uf8+p3eKyifcAf2r7Pq4VEk3wWgEqHM9JKNlhqIoCdAvc2R3JVYqa0RzcZb/hKPln68YowN+bjAF7q1SqoEwlrOu7qq3SLWWLAX5ml7pHjgTwFBwPnDp7+E9x3PVfxEvf02zOvTQH+NDrd+5GFeZgBZ8MP/uhENMKu7RnoqwkzwawkkGHU1A+5o/TE0VMGqc6aYKXQxcgGFXy7XUqJUNz1gyMyQ0GnXHUrwBjCmVGH4mRMi2bPXuGe5rW0qRm7vZZUMPNMVlJkqcGt1TC7VY9Q630uHnr+ma7lKwYC3DzxnDeR2OxSfOYu2EwcypDKUWr9WYapJHRjoXx3tgRgDLxu7UCGBZHktj8QQ9OTl/AHo1P+y5aSRv/H4Gcmtnb+nQdDJSEvrEtgVAMlh8s/O4SUgaUsSHBo9hE//M8I3nHi9flzuKf1XU6w03SgG5L3Rfkqc/DH0ZudWnXwNuG3QePtgkiGtJwaF1MviBIyY0dHEgsHtCLKIQYnnW95lYkhZTnRAm92lNmDxNV/r0ABhBSZJ977g8u/HflRH7Oo7S8YXtqFCHBcjtKeHmBNTLJeqgnOzxNuHPV4bO1s4iAgSX5LgX7c142zcNDqFzAcI3hyQiVZU74k5HDRNqqlZFfpHV1609c=
  distributions: sdist bdist_wheel
  skip_existing: true
  on:
    tags: true
